### ISSUE TITLE
\otimes+TAB in PyJulia

### ISSUE THREAD

**Issue by DiegoGM91** [Jutho/TensorKit.jl#108]
Hi,

I am using PyJulia to call Julia code from Python 3, and I have found an issue when trying to type the tensor product. Namely, \otimes+TAB doesn't work, neither it does copy pasting from Julia (both things tried on terminal on an Ubuntu machine). Is there any solution for this? 

I found [this](https://pyjulia.readthedocs.io/en/latest/limitations.html) in the PyJulia documentation suggesting that it might not be possible, but a workaround would be highly appreciated.

Thanks!

**Comment by lkdvos** [comment]
Hi Diego,
I think that for vectorspaces, you can replace `\otimes+TAB` with `*` and everything should just work. It's definitely a good remark that a non-unicode alternative should also be available for the sectors, which I don't think exists just yet...

**Comment by DiegoGM91** [comment]
Hi Lukas,

Thanks a lot for the quick response!

Unfortunately, I need it to tensor irreps of SU from [here](https://github.com/maartenvd/SUNRepresentations.jl), and `*` doesn't seem to work.

**Comment by lkdvos** [comment]
In that case, you might circumvent the issue with `directproduct` [see definition here](https://github.com/maartenvd/SUNRepresentations.jl/blob/4107f08eb54399491aabf79e768889c6c2a24b05/src/SUNRepresentations.jl#L100). 
In any case, I'll look into fixing this, so let me keep this issue open for now as a reminder?

**Comment by DiegoGM91** [comment]
Cool, thanks Lukas!!

Sure, keeping the issue opened sounds good to me.
