### ISSUE TITLE
"UndefVarError `×` not defined" in Julia REPL

### ISSUE THREAD

**Issue by Yu-BinLi** [Jutho/TensorKit.jl#139]
Dear Professor Jutho,

I am using the representation of the direct product of two groups. 

When I wrote 
`using TensorKit`
`Rep[ℤ₂ × ℤ₂]((0,0)=>2, (1,0)=>2)`
in a Jupyter Notebook, it works well. But when I used these codes in .jl file or in an REPL environment, it showed 
"ERROR: UndefVarError: `×` not defined"

On the other hand, if I wrote, for example
`fuse(Rep[ℤ₂](0 => 2, 1 => 2) ⊠ Rep[ℤ₂](0 => 1))` in a .jl file or an REPL environment
it would give the right output
`Rep[ℤ₂ × ℤ₂]((0, 0)=>2, (1, 0)=>2)`.

Is there any bug or mistake when I was using them?

**Comment by lkdvos** [comment]
Hi Yu-BinLi,

This is indeed strange and should not be happening.
Are you certain that you are also adding `using TensorKit` in the REPL or the .jl files as well? If you are, is it possible that you have already imported a different package that also exports this symbol, such that it should now be qualified?
Can you check if explicitly adding the module (ie `TensorKit.×`) resolves the issue?

I am having some problems reproducing this error, in my REPL this seems to behave just fine. Can you maybe show the output of `Pkg.status()`?

**Comment by Yu-BinLi** [comment]
Thanks Ikdvos. You comment is very helpful.

I have used these packages: 
`TensorKit`, `TensorOperations`, `LinearAlgebra`, `Plots` and `DelimitedFiles`.
 
If I wrote 
`Rep[ℤ₂ × ℤ₂]((0,0)=>2, (1,0)=> 2)` just after `using TensorKit` in a .jl file (then import other packages), it also worked well. But if I first import all these packages by running `using ...`, this error occured. 

The `Pkg.status()` shows![image](https://github.com/user-attachments/assets/4dedca14-3fd3-42d3-94c8-e93e47a946f1)

Now I can at least use `×` normally. Thanks for your time.

**Comment by lkdvos** [comment]
This is due to the interplay with `LinearAlgebra`, which also exports that symbol. Note that the REPL is already trying to tell you that:
```julia
julia> using LinearAlgebra

julia> using TensorKit

julia> @which ×
WARNING: both TensorKit and LinearAlgebra export "×"; uses of it in module Main must be qualified
```

You can fix this by explicitly importing the one from TensorKit:
```julia
julia> using TensorKit: ×

julia> @which ×
TensorKit
```

This is quite common with the interplay between LinearAlgebra and TensorKit.

**Comment by Jutho** [comment]
As a side note, we decided not to overload `LinearAlgebra.:×` because this really has a very different meaning, and thus assigning/adding a completely new meaning to this function would be in violation with Julia's policies. It is a bit regretful that LinearAlgebra claims this symbol for a very specific and limited operation (the cross product, which is only defined between three-dimensional vectors).
