### ISSUE TITLE
Feature request: a more flexible SVD truncation scheme

### ISSUE THREAD

**Issue by Yue-Zhengyuan** [Jutho/TensorKit.jl#164]
Currently, the truncation schemes for SVD either uses a hard dimension cutoff (`truncdim` and `truncspace`) or uses a truncation error cutoff (`truncerr` and `truncbelow`). However, there are situations where it is preferred to grow the SVD dimension gradually. If I directly use the dimension cutoff, at the beginning stage, there will be too many small singular values left, affecting numerical stability. If I use the truncation error cutoff, I may have to manually cut down the produced U, S, Vh tensors (which I haven't figure out how to do yet). 

Is it convenient to add a more flexible truncation scheme which is a composition of a hard dimension cutoff, followed by a further truncation error cutoff to discard small singular values?

**Comment by Confusio** [comment]
I think you can combine different truncation schemes, e.g., `trunc=truncerr(1.0e-10)&truncdim(20)`.

**Comment by Confusio** [comment]
`&` is overloaded as follows:
```julia
function Base.:&(a::MultipleTruncation, b::MultipleTruncation)
    return MultipleTruncation((a.truncations..., b.truncations...))
end
```
