### ISSUE TITLE
Question: solving linear equations

### ISSUE THREAD

**Issue by Yue-Zhengyuan** [Jutho/TensorKit.jl#165]
There's no discussion section in this repo, so I have to ask here...

Suppose that three linear maps are related by `A * X = B`; or more generally, three tensors (possibly fermionic) `A, X, C` are related by some `@tensor` or `@ncon` expression. Is it currently implemented to solve `X` from `A` and `B`, or we have to solve in each symmetry block manually?

**Comment by Jutho** [comment]
If it is `A * X = B`, common linear algebra operations like `inv`, `pinv`, `\` and `/` should work on `(Abstract)TensorMap` instances. If it is some more complicated linear operation like an `@ncon` expression, an alternative may be to solve it using KrylovKit.jl's `linsolve`. That is supposed to be for large-scale operations where you do not want to compute the exact inverse, but if optimal performance is not really necessary, it should deal with small problems just fine.
