### ISSUE TITLE
creating a GenericRepresentationSpace with only one sector

### ISSUE THREAD

**Issue by orialb** [Jutho/TensorKit.jl#17]
Hi,

This is a minor issue, but in the past it was possible to do something like `U₁Space(1=>1)` which now fails. One has to call  `U₁Space((1=>1, ) )` instead.
This could be fixed by defining `GenericRepresentationSpace{G}(d1::Pair; kwargs...)`.

**Comment by Jutho** [comment]
Nice catch; I'll look into this straight away, that should not have happened

**Comment by Jutho** [comment]
Should be fixed on master. Feel free to close after you've confirmed that there are no other issues with the most recent commits.

**Comment by orialb** [comment]
thanks! 
it is indeed fixed now.
