### ISSUE TITLE
Error using a combination of `mul!`, `One()` and blocks of length 1

### ISSUE THREAD

**Issue by lkdvos** [Jutho/TensorKit.jl#171]
I seem to have stumbled on an absolute beauty of a combination of things that breaks:
```julia
using TensorKit
using TensorKit: mul!
using TensorKit.VectorInterface: One, Zero

V = SU2Space(0 => 1, 1 => 1)
A = rand(V, V)
B = rand(V, V)
C = rand(V, V)

mul!(C, A, B, true, false) # works
mul!(C, A, B, true, One()) # stackoverflow

V = SU2Space(0 => 1, 1 => 2)
A = rand(V, V)
B = rand(V, V)
C = rand(V, V)

mul!(C, A, B, true, false) # works
mul!(C, A, B, true, One()) # stackoverflow

V = SU2Space(0 => 2, 1 => 2)
A = rand(V, V)
B = rand(V, V)
C = rand(V, V)

mul!(C, A, B, true, false) # works
mul!(C, A, B, true, One()) # works

V = SU2Space(0 => 3, 1 => 3)
A = rand(V, V)
B = rand(V, V)
C = rand(V, V)

mul!(C, A, B, true, false) # works
mul!(C, A, B, true, One()) # works

V = SU2Space(0 => 4, 1 => 4)
A = rand(V, V)
B = rand(V, V)
C = rand(V, V)

mul!(C, A, B, true, false) # works
mul!(C, A, B, true, One()) # fails
```

I'm currently investigating.

**Comment by lkdvos** [comment]
Turns out that it's a promotion issue: https://github.com/Jutho/VectorInterface.jl/issues/20

The weird behavior is because the promotion is only used if the specialized `2x2` and `3x3` implementations of `mul!` aren't hit.

**Comment by lkdvos** [comment]
This is fixed as of v0.4.8 of VectorInterface. I am not sure if I should bump the minimal compat here to fix this, or can I just close this @Jutho ?

**Comment by Jutho** [comment]
How did you discover this in the first place? Where you just manually trying out alpha and beta combinations? Or this is combination of arguments being generated by `@tensor` or in some of the higher level packages (MPSKit, PEPSKit)?

**Comment by lkdvos** [comment]
In https://github.com/lkdvos/BlockTensorKit.jl/pull/16, I rewrote part of the BlockTensor `mul!` to be more friendly towards eltypes that might be `AbstractTensorMap`, and thus not necessarily have an in-place way of performing the multiplication. In this blocked mul approach, the first write should be in-place with `beta`, but all the ones after that can have `beta=One()`. This generated the problem. I am guessing that we never really bumped into this because typically both `alpha` and `beta` are either of the VectorInterface number type, or `Bool`, combined with regular numbers, but not both VectorInterface mixed with `Bool` with some other number type. I don't know if we really have code that would automatically generate this, but it definitely should be allowed?

**Comment by Jutho** [comment]
Yes it should definitely be allowed. The question is whether it is important to force this fix, or whether it is sufficient to rely on the fact that the patch release will automatically be installed when a user decides to update packages at some point.

**Comment by lkdvos** [comment]
I'm fine with leaving it as is. I changed the compat in BlockTensorKit, as that explicitly fails otherwise, but I would guess it does not come up otherwise.
