### ISSUE TITLE
error when using `svd` with truncation

### ISSUE THREAD

**Issue by orialb** [Jutho/TensorKit.jl#18]
It seems that SVD with truncation is broken due to changes in the iterator interface in Julia. 
Specifically in `_truncate!` there are calls to `start`, `next` and `done` which do not exist anymore (Julia v1.2). As far as I understand all of these were replaced by `iterate`.

Here is a MWE
```julia
S = U₁Space(n=>1 for n in 1:10)
M = TensorMap(rand,Float64, S, S)
svd(M; trunc=truncerr(1e-10))
```

I might try to fix this myself at some point in case you don't get to it before I have time for that (but at the moment I have to go do other work).

**Comment by Jutho** [comment]
Ok, clearly another gap in my set of tests. I'll fix it right away

**Comment by Jutho** [comment]
Fixed on master and added test to prevent failures in the future; awaiting CI but it is looking good. Will tag a new version thereafter.

**Comment by orialb** [comment]
Thanks for the quick fix!

**Comment by orialb** [comment]
Can confirm that this is working now, so I will go ahead and close this issue.
