### ISSUE TITLE
Fail to extract block by specifying sector of each index for (N,0) or (0,N) tensors

### ISSUE THREAD

**Issue by Yue-Zhengyuan** [Jutho/TensorKit.jl#182]
For a `TensorMap` with `N1` > 0 codomain indices and `N2` > 0 domain indices, I can extract its blocks by specifying the sector of each index:
```julia
using TensorKit
V = U1Space(0 => 2, 1 => 2, -1 => 2)
a = TensorMap(randn, Float64, V, V)
I = sectortype(a)
a[(I(1), I(-1))]
```
Output:
```
2×2 StridedViews.StridedView{Float64, 2, Vector{Float64}, typeof(identity)}:
 -1.29546  -0.115814
  1.63631  -0.808197
```
However, if I permute all indices to codomain (or domain), this no longer works:
```julia
a2 = permute(a, ((1,2), ()))
a2[(I(1), I(-1))]
```
I get the error:
```
MethodError: no method matching FusionTree(::Tuple{}, ::U1Irrep, ::Tuple{})
The type `FusionTree` exists, but no method is defined for this combination of argument types when trying to construct it.
```

**Comment by Jutho** [comment]
Thanks for catching this. I can reproduce and will fix this asap.

**Comment by Jutho** [comment]
This is fixed on master, we will tag a new patch release asap.

**Comment by lkdvos** [comment]
One possible way to get around this would be to do something like:

```julia
for (f1, f2) in fusiontrees(a2)
    if f1.uncoupled == (I(-1), I(1))
         @show a2[f1, f2]
    end
end
```

The trick is that this bypasses that step of constructing the fusiontrees by starting from them, and checking if the uncoupled charges are the ones you are looking for.
Would that be sufficient for your current use-case?
