### ISSUE TITLE
norm of empty symmetric tensors

### ISSUE THREAD

**Issue by maartenvd** [Jutho/TensorKit.jl#19]
currently this

`norm(TensorMap(zeros,ComplexF64,ℂ[U₁](1=>1),ℂ[U₁](0=>1)))`

errors. Would it be correct to make this return 0?

**Comment by Jutho** [comment]
Yes this should return 0; I'll look into it.

**Comment by Jutho** [comment]
Can you try with latest master; should be fixed. Reopen if necessary.
