### ISSUE TITLE
step cannot be zero

### ISSUE THREAD

**Issue by maartenvd** [Jutho/TensorKit.jl#21]
I think empty blocks still cause issues, because this fails somewhere deep in strided : 

```
t = TensorMap(rand,ComplexF64,ProductSpace(U₁Space(0=>12, 1=>0, -1=>12, -2=>12)) ← (U₁Space(0=>1)' ⊗ U₁Space(0=>12, 1=>12, -1=>12)))
mul!(similar(t,ComplexF64),t,1/norm(t))
```

**Comment by Jutho** [comment]
Yes the problem is actually with the `U₁Space` constructor; it should just ignore zero-dimensional sectors and remove them.
