### ISSUE TITLE
transpose can hang

### ISSUE THREAD

**Issue by maartenvd** [Jutho/TensorKit.jl#55]
the following hangs

`
t = Tensor(rand,ComplexF64,Rep[SU₂](0=>1));
transpose(t,(),(1,))
`

I quick'n dirty fix may be the following commit
https://github.com/Jutho/TensorKit.jl/commit/c61b531a3f9c68b4184ff3f619509f593c21f7a5

**Comment by Jutho** [comment]
should be fixed on master; also the length zero case was failing (but would probably never have been called by the `@planar` macro).
