### ISSUE TITLE
Automatic Differentiation support

### ISSUE THREAD

**Issue by ErikLW** [Jutho/TensorKit.jl#63]
Hey, 
Is there a way to use automatic differentiation with the TensorMap type and with the @tensor macro?
Best regards,
Erik

**Comment by Jutho** [comment]
In the public version, not yet. @maartenvd and others have been working on support for this (most of it is done) behind the scenes.  Maybe you are interested to get involved?

**Comment by maartenvd** [comment]
I would not be against making the TensorKitAD package public but unregistered?

**Comment by Jutho** [comment]
Sure. I don't think it should be registered as we probably want to reorganise some stuff. It contains TensorOperations specific stuff that is not really TensorKit. I want to invest some time in TensorOperations the next weeks, move CUDA support to a separate package, but maybe make AD support first class, so without the need to load other packages (except of course Zygote or any other AD engine that supports ChainRules.jl), by taking the stuff you have in TensorKitAD.

And maybe then TensorKit itself should also have first class AD support in the same manner.

**Comment by ErikLW** [comment]
> I would not be against making the TensorKitAD package public but unregistered?
Both TensorOperations and TensorKit support for AD would be very useful! If you decide to make the AD support public, let me know! 


> In the public version, not yet. @maartenvd and others have been working on support for this (most of it is done) behind the scenes. Maybe you are interested to get involved?

I have only recently started using Julia, so sadly I don't think I would be of much help.

**Comment by maartenvd** [comment]
https://github.com/quantumghent/TensorKitAD.jl should be publicly visible now? Feel free to open a bug report with any new errors you encounter, when I'm back from holiday I will look at them.
