### ISSUE TITLE
Problem with gradient when using tensors with Float64 and ComplexF64 entries

### ISSUE THREAD

**Issue by philihps** [Jutho/TensorKit.jl#90]
I am trying to compute the gradient of function, that takes a matrix as input and contracts with another tensor. If both tensors have either Float64 or ComplexF64 values, the Zygote gradient works. However, if one has Float64 and the other one ComplexF64 entries, it fails and returns an InexactError: Float64() error. Below I provide a MWE, which has the same behaviour as the actual function I need.

```
normDiff(a, b) = norm(a - b);

A = TensorMap(randn, Float64, ComplexSpace(2), ComplexSpace(2));
B = TensorMap(randn, Float64, ComplexSpace(2), ComplexSpace(2));
Zygote.gradient((x, y) -> normDiff(x, y), A, B)

A = TensorMap(randn, ComplexF64, ComplexSpace(2), ComplexSpace(2));
B = TensorMap(randn, ComplexF64, ComplexSpace(2), ComplexSpace(2));
Zygote.gradient((x, y) -> normDiff(x, y), A, B)

A = TensorMap(randn, Float64, ComplexSpace(2), ComplexSpace(2));
B = TensorMap(randn, ComplexF64, ComplexSpace(2), ComplexSpace(2));
Zygote.gradient((x, y) -> normDiff(x, y), A, B)
```

**Comment by Jutho** [comment]
Could you test this with the master version of TensorKit.jl? There was some fix for the chainrules in the case of mixed scalartype, which was not yet included in the latest registered version. We will provide a version update soon.

**Comment by Gertian** [comment]
I had the same problem and updating TensorKit.jl to the current master fixed it.

**Comment by philihps** [comment]
Thanks, using the current master fixes the problem.

**Comment by lkdvos** [comment]
Tagged in [v12.1.0](https://github.com/Jutho/TensorKit.jl/releases/tag/v0.12.1)
